version: '3'

x-logging: &default-logging
  driver: loki
  options:
    loki-url: "http://localhost:3100/loki/api/v1/push"

services:
  twilio-app:
    build:
      context: .
      dockerfile: dockerfiles/twilio_server.Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - redis
    env_file:
      - .env
    logging: *default-logging

  bolna-app:
    build:
      context: .
      dockerfile: dockerfiles/bolna_server.Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - redis
    env_file:
        - .env
    volumes:
      - ../agent_data:/app/agent_data
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
      - $HOME/.aws/config:/root/.aws/config:ro
    logging: *default-logging

  redis:
    image: "redis:latest"


  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok-config.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
    logging: *default-logging

  plivo-app:
    image: plivo-app:latest
    build:
      context: .
      dockerfile: dockerfiles/plivo_server.Dockerfile
    ports:
      - "8010:8002"
    depends_on:
      - redis 
    env_file:
      - .env
    logging: *default-logging