region: us
version: '2'
authtoken: 2i0OuGhqCmcVMXTTUWkdwKh5V6H_76oEC8mBUA21t1J2rNTX8
tunnels:
  twilio-app:
    addr: twilio-app:8001
    proto: http
  # plivo-app:
  #   addr: twilio-app:8002
  #   proto: http
  bolna-app:
    addr: bolna-app:5001
    proto: http
