region: us
version: '2'
authtoken: 2gXxexY4LgcNqAK2QEbNdfhJPNc_4sP7ByHiVFM9rLmD8a5Qs
tunnels:
  twilio-app:
    addr: twilio-app:8001
    proto: http
  bolna-app:
    addr: bolna-app:5001
    proto: http
